-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 16:36:49 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema greenbelt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `greenbelt` ;
CREATE SCHEMA IF NOT EXISTS `greenbelt` DEFAULT CHARACTER SET utf8 ;
USE `greenbelt` ;

-- -----------------------------------------------------
-- Table `greenbelt`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenbelt`.`users` ;

CREATE TABLE IF NOT EXISTS `greenbelt`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenbelt`.`incidents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenbelt`.`incidents` ;

CREATE TABLE IF NOT EXISTS `greenbelt`.`incidents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `creator_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_incidents_users_idx` (`creator_id` ASC),
  CONSTRAINT `fk_incidents_users`
    FOREIGN KEY (`creator_id`)
    REFERENCES `greenbelt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `greenbelt`.`users_has_incidents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greenbelt`.`users_has_incidents` ;

CREATE TABLE IF NOT EXISTS `greenbelt`.`users_has_incidents` (
  `users_id` INT(11) NOT NULL,
  `incidents_id` INT(11) NOT NULL,
  PRIMARY KEY (`incidents_id`, `users_id`),
  INDEX `fk_users_has_incidents_incidents1_idx` (`incidents_id` ASC),
  INDEX `fk_users_has_incidents_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_incidents_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `greenbelt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_incidents_incidents1`
    FOREIGN KEY (`incidents_id`)
    REFERENCES `greenbelt`.`incidents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
